app:
  port: ':5000'
  cert_file: './cmd/chat/certificate.pem'
  key_file: './cmd/chat/key.pem'
  time_format: '2006-01-02T15:04:05'

# amqp://guest:guest@localhost:5672/
rabbitmq:
  host: 'amqp://%s:%s@%s:%s/'
  user: 'dev'
  password: 'password'
  address: '192.168.0.101'
  port: '5672'
  exchange_name: 'message.for.*'
  exchange_type: 'topic'
  exchange_durable: true
  exchange_auto_delete: false
  exchange_internal: false
  exchange_no_wait: false
  topic_mandatory: false
  topic_immediate: false
  content_type: "application/json"

cache:
  address: '192.168.0.105'
  port: ':6379'
  password: 'Awesome85**'
  db: 0
  pool_size: 25
  minimum_idle_connections: 10
  maximum_retries: 1
  online_user_key_format: 'online.user.%s'

producer:
  brokers: ['192.168.0.105:9092']
  topic: 'store.chat.message'
  batch_size: 1
  batch_timeout: 10

health:
  port: ':8120'
  shutdown_endpoint: '/api/v1/superhero_chat_health/shutdown'
  content_type: 'application/json'