db:
  host: localhost
  port: 3306
  user: root
  password:
  name: superhero_chat

# amqp://guest:guest@localhost:5672/
rabbitmq:
  host: 'amqp://%s:%s@%s:%d/'
  user: superhero
  password: match
  address: localhost
  port: 5672